import { pgTable, serial, text, integer, boolean, timestamp, date } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { churchesTable } from "./churches";

export const usersTable = pgTable("users", {
  id: serial("id").primaryKey(),
  churchId: integer("church_id").notNull().references(() => churchesTable.id),
  email: text("email").notNull().unique(),
  passwordHash: text("password_hash"),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  preferredName: text("preferred_name"),
  phoneNumber: text("phone_number"),
  profilePhotoUrl: text("profile_photo_url"),
  dateOfBirth: date("date_of_birth"),
  ageGroup: text("age_group"),
  gender: text("gender"),
  memberStatus: text("member_status", { enum: ["visitor", "member", "active_member", "inactive"] }).notNull().default("member"),
  profileStatus: text("profile_status", { enum: ["visitor", "pending_review", "approved_member", "archived_duplicate"] }).notNull().default("pending_review"),
  profileCompletionPercent: integer("profile_completion_percent").notNull().default(0),
  ministryDepartment: text("ministry_department"),
  joinDate: date("join_date"),
  baptismStatus: text("baptism_status", { enum: ["baptized", "not_baptized", "unknown"] }).notNull().default("unknown"),
  smallGroup: text("small_group"),
  servingStatus: text("serving_status", { enum: ["serving", "not_serving", "interested"] }).notNull().default("not_serving"),
  preferredContactMethod: text("preferred_contact_method", { enum: ["phone", "email", "text"] }).notNull().default("email"),
  maritalStatus: text("marital_status"),
  occupation: text("occupation"),
  preferredLanguage: text("preferred_language"),
  emergencyContactName: text("emergency_contact_name"),
  emergencyContactPhoneNumber: text("emergency_contact_phone_number"),
  emergencyContactRelationship: text("emergency_contact_relationship"),
  streetAddress: text("street_address"),
  apartmentUnit: text("apartment_unit"),
  city: text("city"),
  state: text("state"),
  zipCode: text("zip_code"),
  country: text("country"),
  role: text("role", { enum: ["admin", "member"] }).notNull().default("member"),
  adminLevel: text("admin_level", { enum: ["super_admin", "pastor", "minister"] }),
  assignedMinistry: text("assigned_ministry"),
  firstTimeVisitor: boolean("first_time_visitor"),
  interestedInMembership: boolean("interested_in_membership"),
  wantsContact: boolean("wants_contact"),
  ministryInterest: text("ministry_interest"),
  discipleshipInterest: boolean("discipleship_interest"),
  prayerRequest: text("prayer_request"),
  accountStatus: text("account_status", { enum: ["active", "pending", "disabled"] }).notNull().default("active"),
  createdByUserId: integer("created_by_user_id"),
  clerkUserId: text("clerk_user_id").unique(),
  invitedAt: timestamp("invited_at", { withTimezone: true }),
  inviteAcceptedAt: timestamp("invite_accepted_at", { withTimezone: true }),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  isActive: boolean("is_active").notNull().default(true),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});

export const insertUserSchema = createInsertSchema(usersTable).omit({ id: true, createdAt: true, updatedAt: true });
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof usersTable.$inferSelect;
